name: Publish Docker image to GitHub Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/sq4ind/adguardhome-lancache-dns
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha

      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:latest
            ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:${{ steps.date.outputs.date }}

      - name: Generate Commit Log
        id: generate_commit_log
        run: |
          if [ $(git tag | wc -l) -gt 1 ]; then
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))
            COMMIT_LOG=$(git log $PREVIOUS_TAG..HEAD --pretty=format:"- %s")
            echo "::set-output name=commit_log::$COMMIT_LOG"
          else
            echo "::set-output name=commit_log::Initial Release"
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            New release of AdGuardHome-Lancache-DNS.
            
            Docker images available:
            - `ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:latest`
            - `ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:${{ steps.date.outputs.date }}`
            
            ### Commits
            ${{ steps.generate_commit_log.outputs.commit_log }}
          draft: false
          prerelease: false