name: Publish Docker image and Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract version from tag
        id: extract_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:latest
            ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:${{ env.version }}
            sq4ind/adguardhome-lancache-dns:latest
            sq4ind/adguardhome-lancache-dns:${{ env.version }}

      - name: Generate commit log
        id: generate_commit_log
        run: |
          echo "::set-output name=commit_log::$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:'- %s')"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.version }}
          body: |
            New release of AdGuardHome-Lancache-DNS.

            Docker images available:
            - `ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:latest`
            - `ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:${{ env.version }}`

            ### Commits
            ${{ steps.generate_commit_log.outputs.commit_log }}
          draft: false
          prerelease: false