name: Publish Docker image and Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from tag
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:latest
            ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:${{ steps.extract_version.outputs.version }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          body: |
            New release of AdGuardHome-Lancache-DNS.
            
            Docker images available:
            - `ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:latest`
            - `ghcr.io/${{ github.repository }}/adguardhome-lancache-dns:${{ steps.extract_version.outputs.version }}`
            
            ### Commits
            ${{ steps.generate_commit_log.outputs.commit_log }}
          draft: false
          prerelease: false
